owner: PYU224
repo: status
sites:
  - name: ぬくもりすきー
    url: https://misskey.nukumori-sky.net
  - name: 33-4 Blog & Services
    url: https://33-4.me
  - name: 野獣動画2nd
    url: https://810video.com
  - name: 810Chat
    url: https://chat.810video.com
