owner: PYU224
repo: server-status
sites:
  - name: ぬくもりすきー
    url: https://misskey.nukumori-sky.net
  - name: 33-4 Blog & Services
    url: https://33-4.me
  - name: 野獣動画2nd
    url: https://810video.com
  - name: 810Chat
    url: https://chat.810video.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /server-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
